import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProviderWrapper } from '@/app/context/theme-provider'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProviderWrapper attribute='class' defaultTheme="li" enableSystem>
        <body className={cn(`min-h-screen bg-background font-Arial  align-center justify-center text-center`)}>
          {children}
        </body>
      </ThemeProviderWrapper>
    </html>
  )
}
